apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- .git\info\exclude
- TodoList\config-maps.yaml
- TodoList\postgres-service.yaml
- TodoList\postgres.yaml
- TodoList\secret.yaml
- TodoList\todobackend-service.yaml
- TodoList\todobackend.yaml
- TodoList\todoui-service.yaml
- TodoList\todoui.yaml
